FROM code.forgejo.org/forgejo/runner:3.3.0

USER root

COPY scripts/runner-entrypoint.sh /usr/local/bin/run.sh

RUN chmod 755 /usr/local/bin/run.sh

RUN ln -s /usr/local/bin/run.sh /usr/local/bin/entrypoint.sh

COPY conf/runner.yml /etc/runner.yml

RUN chmod 644 /etc/runner.yml

USER git

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
