---
# Create needed zfs directories
- name: Create needed directories for mounting with nas_dirs
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: '0755'
  with_items: "{{ file_server_dirs }}"
  when:
      - not ansible_check_mode

- name: Setup ZFS mountpoints
  ansible.builtin.command: "{{ item }}"
  changed_when: false
  loop:
      - "zfs set mountpoint={{ file_server_mount_dir }} {{ file_server_main_pool }}"
      - "zfs set canmount=on {{ file_server_main_pool }}"
  when:
      - not ansible_check_mode
      - not docker_testing

- name: Set ACL type for main pool
  ansible.builtin.command: "zfs set acltype=posixacl {{ file_server_main_pool }}"
  changed_when: false
  when:
      - not docker_testing

- name: Enable needed ZFS services
  ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: true
  with_items:
      - zfs-import-cache
      - zfs-import-scan
      - zfs-mount
      - zfs-share
      - zfs-zed
      - zfs.target
  when:
      - not ansible_check_mode
      - not docker_testing

- name: Install gen-backup script
  ansible.builtin.copy:
      src: "{{ scripts_dir }}/gen-backup"
      dest: "/usr/local/bin/gen-backup"
      owner: root
      group: root
      mode: '0755'
      force: true

- name: Add daily gen-zfs-snapshot cron script
  ansible.builtin.copy:
      src: "{{ scripts_dir }}/gen-zfs-snapshots"
      dest: "/etc/cron.daily/cron-gen-zfs-snapshots"
      owner: root
      group: root
      mode: '0755'
      force: true

- name: Install prune-zfs-snapshots script
  ansible.builtin.copy:
      src: "{{ scripts_dir }}/prune-zfs-snapshots"
      dest: "/usr/sbin/prune-zfs-snapshots"
      owner: root
      group: root
      mode: '0755'
      force: true

- name: Install zfs-prune-snapshots cron job to run every hour
  ansible.builtin.cron:
      name: "ZFS snapshot cleanup every hour"
      minute: "0"
      job: "/usr/sbin/zfs-prune-snapshots -v 1M >> /var/log/cron/zfs-prune-snapshots.log 2>&1"
