# Loads default set of integrations. Do not remove.
default_config:
  homeassistant:
    media_dirs:
      media: /config/media

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.30.33.0/24
    - 10.89.5.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

mobile_app: # ha's ios/android app
media_source: # ha's local media discovery
