---
- name: Install haproxy package
  ansible.builtin.dnf:
      name:
          - haproxy
      state: present
      update_cache: true
  when:
      - ansible_os_family in ['RedHat', 'CentOS', 'Rocky']

- name: Create needed directories
  ansible.builtin.file:
      path: "{{ item.path }}"
      state: directory
      mode: '0755'
  when: item.when|bool is true
  loop:
      - { path: /etc/haproxy, when: true }
      - { path: /etc/haproxy/certs, when: true }
      - { path: /etc/haproxy/backends, when: true }
      - { path: /etc/haproxy/maps, when: true }

- name: Add service file
  ansible.builtin.copy:
      src: haproxy.service
      dest: "/usr/lib/systemd/system/haproxy.service"
      owner: root
      group: root
      mode: '0644'
  when: ansible_os_family in ['RedHat', 'CentOS', 'Rocky']

- name: Remove default configuration file
  ansible.builtin.file:
      state: absent
      path: "/etc/haproxy/haproxy.cfg"

- name: Add configuration file
  ansible.builtin.copy:
      src: haproxy.conf
      dest: "/etc/haproxy/haproxy.conf"
      owner: root
      group: root
      mode: '0644'

- name: Add rsyslog specific configuration
  ansible.builtin.copy:
      src: haproxy-rsyslog.conf
      dest: "/etc/rsyslog.d/haproxy.conf"
      owner: root
      group: root
      mode: '0644'
  when: ansible_os_family in ['RedHat', 'CentOS', 'Rocky']

- name: Reload systemd
  ansible.builtin.systemd:
      daemon_reload: true
