---
# entrypoint tasks file for role

- name: Assert supported distributions and versions for this role
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_major_version >= '8' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_major_version >= '8' )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version >= '30' )
        ) or
        ( ansible_distribution == "Rocky" and ( ansible_distribution_major_version >= '8' )
        ) or
        ( ansible_distribution == "OpenWrt" and ( ansible_distribution_major_version >= '21' )
        ) or
        ( ansible_distribution == "Alpine" and ( ansible_distribution_major_version >= '3' )
        )

- name: Update and upgrade system
  action: "{{ ansible_pkg_mgr }}"
  args:
    update_only: yes
    update_cache: yes

- import_tasks: install.yml