---
# defaults file for file-server role

file_server_main_pool: storage
file_server_mount_dir: /mnt/storage

# array of directories to create in the main pool
file_server_dirs:
  - "{{ file_server_mount_dir }}/share"
  - "{{ file_server_mount_dir }}/media"
  - "{{ file_server_mount_dir }}/backup"
  - "{{ file_server_mount_dir }}/ai"

# refer to scripts directory outside of roles two directories down.
scripts_dir: "{{ playbook_dir }}/../scripts"
