---
#
# Configures the k3s installation and sets up kubectl and helm
#

# Download helm installation script
- name: Download helm installation script
  ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      dest: /tmp/get_helm.sh
      mode: "0755"
  when: k3s_install_exec == "server"

# Create kubectl configuration directory
- name: Create kubctl configuration directory
  ansible.builtin.file:
      path: /root/.kube
      state: directory
      mode: "0755"
  when: k3s_install_exec == "server"

# Copy kubectl configuration
- name: Copy kubectl configuration
  ansible.builtin.copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /root/.kube/config
      mode: "0644"
      remote_src: true
  when: k3s_install_exec == "server"

# Generate kubectl bash completion script
- name: Generate kubectl bash completion script
  ansible.builtin.shell: kubectl completion bash > /etc/bash_completion.d/kubectl
  args:
      creates: /etc/bash_completion.d/kubectl
  when: k3s_install_exec == "server"

# Install helm using the downloaded script
- name: Install helm
  ansible.builtin.command: /tmp/get_helm.sh
  args:
      creates: /usr/local/bin/helm
  when: k3s_install_exec == "server"

# Generate helm bash completion script
- name: Generate helm bash completion script
  ansible.builtin.shell: helm completion bash > /etc/bash_completion.d/helm
  args:
      creates: /etc/bash_completion.d/helm
  when: k3s_install_exec == "server"

# Label agent nodes with the agent role if k3s_install_exec is "agent"
- name: Label agent nodes
  ansible.builtin.command: kubectl label node {{ item }} node-role.kubernetes.io/agent=true --overwrite
  changed_when: false
  loop: "{{ groups['internal_servers'] | difference([inventory_hostname]) }}"
  when: k3s_install_exec == "server"
