---
#
# Install k3s on the target node(s)
#

# Download the k3s installation script on the target node(s)
- name: Download k3s installation script
  ansible.builtin.get_url:
      url: https://get.k3s.io
      dest: /tmp/k3s_install.sh
      mode: "0755"

# Set the tls-san arguments if k3s_tls_san_list is defined
- name: Construct tls-san arguments
  ansible.builtin.set_fact:
      k3s_tls_san_args: "--tls-san {{ k3s_tls_san_list | default([]) | join(' --tls-san ') }}"
  when: k3s_tls_san_list is defined and k3s_tls_san_list | length > 0

# Add k3s-config.j2 file if it exists
- name: Add k3s config file if it exists
  ansible.builtin.template:
      src: k3s-config.j2
      dest: /tmp/k3s-config.yaml
      mode: "0644"
      force: true
  when: k3s_install_exec == "server"
  register: k3s_config_file

# Install k3s server using the installation script
- name: Install k3s server
  ansible.builtin.command: "/tmp/k3s_install.sh server"
  environment:
      # If k3s_haproxy_disabled is false, add traefik and servicelb disable flags
      # into INSTALL_K3S_EXEC. If true, do not add them.
      K3S_CONFIG_FILE: "/tmp/k3s-config.yaml"
      INSTALL_K3S_VERSION: "{{ k3s_install_version }}"
  args:
      creates: /usr/local/bin/k3s
  when:
      - k3s_install_exec == "server"
      - k3s_config_file is not failed

# Wait for the node-token file to be created
- name: Wait for node-token
  ansible.builtin.wait_for:
      path: /var/lib/rancher/k3s/server/node-token
  when: k3s_install_exec == "server"

# Register the node-token file on the server
- name: Register node-token file access mode
  ansible.builtin.stat:
      path: /var/lib/rancher/k3s/server
  register: k3s_p
  when: k3s_install_exec == "server"

# Change file access node-token to be readable by others
- name: Change file access node-token
  ansible.builtin.file:
      path: /var/lib/rancher/k3s/server
      mode: g+rx,o+rx
  when: k3s_install_exec == "server"

# Read the node-token from the server node
- name: Read node-token from server node
  ansible.builtin.slurp:
      src: /var/lib/rancher/k3s/server/node-token
  register: k3s_k3s_node_token
  when: k3s_install_exec == "server"

# Set k3s_token fact from the node-token content
- name: Set token fact
  ansible.builtin.set_fact:
      k3s_token: "{{ k3s_k3s_node_token['content'] | b64decode | regex_replace('\n', '') }}"
  when: k3s_install_exec == "server"

# Display k3s token
- name: Display k3s token
  ansible.builtin.debug:
      msg: "k3s token: {{ k3s_token }}"
  when: k3s_install_exec == "server"

# Set token value from the first server to all other agents
- name: Set token for agent nodes
  ansible.builtin.set_fact:
      k3s_token: "{{ hostvars[groups['internal_servers'][0]]['k3s_token'] }}"
  when:
      - k3s_install_exec == "agent"
      - groups['internal_servers'] is defined
      - groups['internal_servers'] | length > 0

# Verify that k3s-server service is running
- name: Wait for k3s server to be ready
  ansible.builtin.command: "kubectl get nodes"
  changed_when: false
  register: k3s_server_ready
  retries: 10
  delay: 15
  until: k3s_server_ready.rc == 0
  when: k3s_install_exec == "server"

# Install k3s agent
- name: Install k3s agent
  ansible.builtin.command: "/tmp/k3s_install.sh agent"
  environment:
      K3S_TOKEN: "{{ k3s_token }}"
      K3S_URL: "https://{{ k3s_install_url_host }}:6443"
      INSTALL_K3S_VERSION: "{{ k3s_install_version }}"
  args:
      creates: /usr/local/bin/k3s
  when:
      - k3s_install_exec == "agent"
      - k3s_token is not none or k3s_token != ""

# Verify that k3s-agent service is running
- name: Ensure k3s service is running
  ansible.builtin.systemd:
      name: k3s-agent
      state: started
      enabled: true
  when: k3s_install_exec == "agent"

# Verify that k3s-server service is running
- name: Verify k3s installation
  ansible.builtin.command: k3s --version
  register: k3s_version
  changed_when: false

# Display installed k3s version
- name: Display installed k3s version
  ansible.builtin.debug:
      msg: "Installed k3s version: {{ k3s_version.stdout | regex_replace('\n', '') }}"

# Install iscsi-initiator-utils package
- name: Install iscsi-initiator-utils package
  ansible.builtin.package:
      name: iscsi-initiator-utils
      state: present

# Get initiator name from the system
- name: Get initiator name from each system
  ansible.builtin.command: iscsi-iname
  register: k3s_iscsi_iname
  changed_when: false
  failed_when: false

# Add iscsi_iname to facts
- name: Add iscsi_iname to facts
  ansible.builtin.set_fact:
      k3s_iscsi_iname: "{{ k3s_iscsi_iname.stdout }}"
  when:
      - k3s_iscsi_iname is defined
      - k3s_iscsi_iname.stdout != ""

# Write iscsi_iname to /etc/iscsi/initiatorname.iscsi
- name: Write iscsi_iname to /etc/iscsi/initiatorname.iscsi
  ansible.builtin.copy:
      content: 'InitiatorName="{{ k3s_iscsi_iname }}"'
      dest: /etc/iscsi/initiatorname.iscsi
      mode: "0644"
  when:
      - k3s_iscsi_iname is defined
      - k3s_iscsi_iname != ""

# Ensure iscsi service is enabled and started
- name: Ensure iscsi service is enabled and started
  ansible.builtin.systemd:
      name: iscsid
      state: started
      enabled: true
