---
- name: Create needed directories
  file:
    path: "{{ item.path }}"
    state: directory
  when: item.when|bool == true
  loop:
    - { path: /opt/containers, when: true }
    - { path: /opt/containers/minio, when: true }
    - { path: /opt/containers/minio/data, when: true }

- name: Allow minio daemon in firewalld
  ansible.posix.firewalld:
    port: 9093/tcp
    permanent: yes
    immediate: yes
    zone: public
    state: enabled

- name: Allow minio daemon in firewalld
  ansible.posix.firewalld:
    port: 9094/tcp
    permanent: yes
    immediate: yes
    zone: public
    state: enabled

- name: Make sure to clear any existing configuration files
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - /opt/containers/minio/config/minio.env
      - /opt/containers/minio/config/minio.label

- name: Configure enviroment configuration
  lineinfile:
    path: "/opt/containers/minio/config/minio.env"
    state: present
    create: yes
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ minio_environment_variables }}"

- name: Configure label configuration
  lineinfile:
    path: "/opt/containers/minio/config/minio.label"
    state: present
    create: yes
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ minio_labels }}"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable service and ensure it is not masked
  systemd:
    name: minio-container
    enabled: yes
    masked: no

- name: Make sure service is running
  systemd:
    state: restarted
    name: minio-container
