---
- name: Add container service file
  copy:
    src: minio-container.service
    dest: "/usr/lib/systemd/system/minio-container.service"
    owner: root
    group: root
  when: ansible_os_family in ['RedHat', 'CentOS', 'Rocky']

- name: Add container run script
  copy:
    src: run-minio-container.sh
    dest: "/usr/local/bin/run-minio-container"
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family in ['RedHat', 'CentOS', 'Rocky']

- name: Reload systemd
  systemd:
    daemon_reload: yes
