FROM alpine:3

RUN apk add --update \
    tzdata \
    bash \
    shadow \
    ovmf \
    seabios \
    libvirt-client \
    libvirt-daemon \
    libvirt-common-drivers \
    libvirt-qemu \
    qemu-system-x86_64 \
    qemu-audio-alsa \
    qemu-audio-oss \
    qemu-audio-pa \
    qemu-audio-sdl \
    qemu-audio-spice \
    qemu-block-curl \
    qemu-block-dmg-bz2 \
    qemu-block-nfs \
    qemu-block-ssh \
    qemu-chardev-spice \
    qemu-hw-display-qxl \
    qemu-hw-display-virtio-gpu \
    qemu-hw-display-virtio-gpu-pci \
    qemu-hw-display-virtio-vga \
    qemu-hw-usb-redirect \
    qemu-img \
    monit \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /var/lib/libvirt/images/

RUN rm -rf /etc/init.d /etc/conf.d /etc/inittab /etc/runlevels /etc/rc.conf /etc/logrotate.d /etc/logrotate.conf /etc/periodic

COPY virtd.monitrc /etc/monitrc

RUN chmod 0700 /etc/monitrc

VOLUME ["/var/run/libvirt/", "/var/lib/libvirt", "/sys/fs/cgroup"]

CMD ["/usr/sbin/monit", "-I", "-c", "/etc/monitrc"]
