#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 John Unland

set -e

msg() {
    echo " >>> $1"
}

DATE_TIME=$(date "+%A %B %d %T %Y")
USERS="root"

# Detect if we are using podman or docker
if CONTAINER_CMD=$(command -v podman 2>/dev/null); then
    :
elif CONTAINER_CMD=$(command -v docker 2>/dev/null); then
    :
else
    msg "Error: podman or docker is not installed."
    exit 1
fi

msg "Start $0 script @ $DATE_TIME"

# Loop through all users
for user in $USERS; do
    # Make sure user exists
    if ! id -u "$user" >/dev/null 2>&1; then
        msg "User does not exist: $user"
        continue
    fi

    msg "Cleaning container system for $user"
    su - "$user" -c 'exec "$@"' -- "$CONTAINER_CMD" system prune
done

exit 0
