#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 John Unland

set -euo pipefail

msg() {
    echo " >>> $1"
}

LEGO_DNS_TYPE=cloudflare
LEGO_DATA_DIR="$HOME/.lego"
LEGO_CERT_DIR="$LEGO_DATA_DIR/certificates"
CF_API_EMAIL=myemail@example.com
CF_DNS_API_TOKEN=mytoken
CF_DOMAIN="*.example.com"
CERT_NAME=${CF_DOMAIN//\*/_}
CERT_FILE="$LEGO_CERT_DIR/$CERT_NAME.crt"
KEY_FILE="$LEGO_CERT_DIR/$CERT_NAME.key"

export CF_DNS_API_TOKEN CF_API_EMAIL CF_DOMAIN

# Check if certificates exist in cert directory.
if [ -f "$CERT_FILE" ]; then
    msg "Certificate exists. Renewing certificate..."
    lego --accept-tos --path "$LEGO_DATA_DIR" \
        --dns "$LEGO_DNS_TYPE" --domains "$CF_DOMAIN" --email "$CF_API_EMAIL" renew --no-bundle
    exit 0
fi

# If no certificates exist, create new ones.
msg "No certificate found. Creating new certificate..."

lego --accept-tos --path "$LEGO_DATA_DIR" \
    --dns "$LEGO_DNS_TYPE" --domains "$CF_DOMAIN" --email "$CF_API_EMAIL" run --no-bundle

msg "Setting permissions on cert(s)..."
chmod 644 "$CERT_FILE"

msg "Setting permissions on key(s)..."
chmod 600 "$KEY_FILE"

exit 0
