#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 John Unland

set -euo pipefail

msg() {
  printf ' >>> %s\n' "$1"
}

DATE_TIME=$(date "+%A %B %d %T %Y")
SOURCE_DIR="/mnt/storage-fast/tmp/streams"
DEST_DIR="/mnt/storage-slow/.stash/streams"

msg "Start $0 script @ $DATE_TIME"

# Make sure source and destination directories exist.
if [ ! -d "$SOURCE_DIR" ]; then
  msg "Source directory not found..."
  exit 1
fi

if [ ! -d "$DEST_DIR" ]; then
  msg "Destination directory not found..."
  exit 1
fi

while IFS= read -r -d '' file; do
    msg "Processing file: $file"

    PARENT_DIR=${file%/*}
    BASE_DIR=${PARENT_DIR##*/}
    DESTINATION_DIR="$DEST_DIR/$BASE_DIR"

    msg "Creating destination directory: $DESTINATION_DIR"
    mkdir -p -- "$DESTINATION_DIR"

    # Move file to destination directory using rsync
    msg "Moving file to destination directory: $DESTINATION_DIR"
    rsync -av --remove-source-files -- "$file" "$DESTINATION_DIR/"
done < <(find "$SOURCE_DIR" -type f -name '*.mp4' ! -name '*.temp.mp4' -print0)

#chown stash:stash -R $DEST_DIR/..

msg "Removing empty source directories..."
find "$SOURCE_DIR" -depth -type d -empty -delete

msg "Removing empty destination directories..."
find "$DEST_DIR" -depth -type d -empty -delete

exit 0
