#!/bin/bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2010 Michael Lustfield <mtecknology@ubuntu.com>, 2016 Andrew Salkeld (ajsalkeld) <andrew@ajsalkeld.com>
# Copyright (C) 2026 John Unland (Forked with modifications)

set -euo pipefail

##
# Default Settings
##

if ! command -v nginx >/dev/null 2>&1; then
    echo "${0##*/}: ERROR: nginx is not installed."
    exit 1
fi

NGINX_CONF_FILE="$(nginx -V 2>&1 | awk '{for (i = 1; i <= NF; i++) if ($i ~ /^--conf-path=/) {sub(/^--conf-path=/, "", $i); print $i; exit}}')"

if [[ -z "$NGINX_CONF_FILE" ]]; then
    echo "${0##*/}: ERROR: Unable to determine the Nginx configuration path."
    exit 1
fi

NGINX_CONF_DIR="${NGINX_CONF_FILE%/*}"
NGINX_SITES_AVAILABLE="$NGINX_CONF_DIR/sites-available"
NGINX_SITES_ENABLED="$NGINX_CONF_DIR/sites-enabled"
SELECTED_SITE="${2-}"

shopt -s nullglob

##
# Script Functions
##

ngx_enable_site() {
    [[ ! "$SELECTED_SITE" ]] &&
        ngx_select_site "not_enabled"

    ngx_validate_site
    [[ ! -e "$NGINX_SITES_AVAILABLE/$SELECTED_SITE" ]] &&
        ngx_error "Site does not appear to exist."
    [[ -e "$NGINX_SITES_ENABLED/$SELECTED_SITE" || -L "$NGINX_SITES_ENABLED/$SELECTED_SITE" ]] &&
        ngx_error "Site appears to already be enabled"

    ln -sf -- "$NGINX_SITES_AVAILABLE/$SELECTED_SITE" "$NGINX_SITES_ENABLED/$SELECTED_SITE"
    ngx_reload
}

ngx_disable_site() {
    [[ ! "$SELECTED_SITE" ]] &&
        ngx_select_site "is_enabled"

    ngx_validate_site
    [[ ! -e "$NGINX_SITES_AVAILABLE/$SELECTED_SITE" ]] &&
        ngx_error "Site does not appear to be \'available\'. - Not Removing"
    [[ ! -e "$NGINX_SITES_ENABLED/$SELECTED_SITE" && ! -L "$NGINX_SITES_ENABLED/$SELECTED_SITE" ]] &&
        ngx_error "Site does not appear to be enabled."

    rm -f -- "$NGINX_SITES_ENABLED/$SELECTED_SITE"
    ngx_reload
}

ngx_edit_site() {
    [[ ! "$SELECTED_SITE" ]] &&
        ngx_select_site "not_enabled"

    ngx_validate_site
    [[ ! -e "$NGINX_SITES_AVAILABLE/$SELECTED_SITE" ]] &&
        ngx_error "Site does not appear to exist."

    nano -- "$NGINX_SITES_AVAILABLE/$SELECTED_SITE"
}

ngx_list_site() {
    echo "Available sites:"
    ngx_sites "available"
    echo "Enabled Sites"
    ngx_sites "enabled"
}

##
# Helper Functions
##

ngx_select_site() {
    local -a sites_avail sites_en sites

    sites_avail=("$NGINX_SITES_AVAILABLE"/*)
    sites_en=("$NGINX_SITES_ENABLED"/*)

    case "$1" in
        not_enabled) mapfile -t sites < <(comm -13 <(printf '%s\n' "${sites_en[@]##*/}") <(printf '%s\n' "${sites_avail[@]##*/}")) ;;
        is_enabled) mapfile -t sites < <(comm -12 <(printf '%s\n' "${sites_en[@]##*/}") <(printf '%s\n' "${sites_avail[@]##*/}")) ;;
    esac

    [[ "${#sites[@]}" -gt 0 ]] || ngx_error "No matching sites available."
    ngx_prompt "${sites[@]}"
}

ngx_prompt() {
    local -a sites=("$@")
    local i

    echo "SELECT A WEBSITE:"
    for i in "${!sites[@]}"; do
        printf '%s:\t%s\n' "$i" "${sites[$i]}"
    done

    IFS= read -r -p "Enter number for website: " i
    [[ "$i" =~ ^[0-9]+$ && "$i" -lt "${#sites[@]}" ]] ||
        ngx_error "Invalid site selection."
    SELECTED_SITE="${sites[$i]}"
}

ngx_sites() {
    local -a files
    local file

    case "$1" in
        available) dir="$NGINX_SITES_AVAILABLE" ;;
        enabled) dir="$NGINX_SITES_ENABLED" ;;
    esac

    files=("$dir"/*)
    for file in "${files[@]}"; do
        printf '\t%s\n' "${file#"$dir"/}"
    done
}

ngx_validate_site() {
    [[ "$SELECTED_SITE" != */* && "$SELECTED_SITE" != "." && "$SELECTED_SITE" != ".." ]] ||
        ngx_error "Invalid site name."
}

ngx_reload() {
    read -p "Would you like to reload the Nginx configuration now? (Y/n) " reload
    [[ "$reload" != "n" && "$reload" != "N" ]] && systemctl reload nginx
}

ngx_reload_now() {
    systemctl reload nginx
}

ngx_error() {
    echo -e "${0##*/}: ERROR: $1"
    [[ "$2" ]] && ngx_help
    exit 1
}

ngx_help() {
    echo "Usage: ${0##*/} [options]"
    echo "Options:"
    echo -e "\t<-e|--enable> <site>\tEnable site"
    echo -e "\t<-d|--disable> <site>\tDisable site"
    echo -e "\t<-x|--edit>\t\tEdit site"
    echo -e "\t<-r|--reload>\t\tReload Nginx"
    echo -e "\t<-l|--list>\t\tList sites"
    echo -e "\t<-h|--help>\t\tDisplay help"
    echo -e "\n\tIf <site> is left out a selection of options will be presented."
    echo -e "\tIt is assumed you are using the default sites-available and"
    echo -e "\tsites-enabled located at $NGINX_CONF_DIR."
}

##
# Core Piece
##

case "$1" in
    -e | --enable) ngx_enable_site ;;
    -d | --disable) ngx_disable_site ;;
    -x | --edit) ngx_edit_site ;;
    -r | --reload) ngx_reload_now ;;
    -l | --list) ngx_list_site ;;
    -h | --help) ngx_help ;;
    *)
        ngx_error "No Options Selected" 1
        ngx_help
        ;;
esac
