#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 John Unland

set -euo pipefail

msg() {
    echo " >>> $1"
}

DATE_TIME=$(date "+%A %B %d %T %Y")
BACKUP_DIR="/mnt/storage/backup"
IMPORT_DATE="20231217"

# Detect if we are using podman or docker
if [ -x "$(command -v podman)" ]; then
    CONTAINER_CMD="podman"
elif [ -x "$(command -v docker)" ]; then
    CONTAINER_CMD="docker"
else
    msg "Error: podman or docker is not installed."
    exit 1
fi

# Make sure BACKUP_DIR is set
if [ -z "$BACKUP_DIR" ]; then
    msg "Error: BACKUP_DIR is not set."
    exit 1
fi

# Make sure directory is mounted and or exists
if [ ! -d "$BACKUP_DIR" ]; then
    msg "Backup directory does not exist: $BACKUP_DIR"
    exit 1
fi

msg "Start $0 script @ $DATE_TIME"

shopt -s nullglob

# Loop through all container backup volumes.
for volume in "$BACKUP_DIR"/podman-vol-*-"$IMPORT_DATE".tar.gz; do
    volume_name=${volume##*/}
    volume_name=${volume_name%.tar.gz}
    volume_name=${volume_name%-"$IMPORT_DATE"}
    volume_name=${volume_name#podman-vol-}

    # Create volume if it does not exist.
    if ! "$CONTAINER_CMD" volume inspect "$volume_name" >/dev/null 2>&1; then
        msg "Creating volume: $volume_name"
        "$CONTAINER_CMD" volume create "$volume_name"
    fi

    msg "Restoring volume: $volume_name"
    gzip -dc "$volume" | "$CONTAINER_CMD" volume import "$volume_name" -
done
