#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 John Unland

set -e

msg() {
    echo " >>> $1"
}

DATE_TIME=$(date +%m-%d-%Y-%s)

msg "Start $0 script @ $DATE_TIME"

# Make sure zfs is installed
if ! command -v zpool >/dev/null 2>&1; then
    msg "zpool command not found..."
    exit 1
fi

# Run scrub on all ZFS pools
pools=$(zpool list -H -o name)
printf '%s\n' "$pools" | while IFS= read -r pool; do
    [ -n "$pool" ] || continue

    TIME_SCRUB=$(date +%m-%d-%Y-%s)
    msg "Running scrub on $pool @ $TIME_SCRUB ..."
    zpool scrub "$pool"
done

exit 0
