#!/bin/bash
# SPDX-License-Identifier: WTFPL
# Copyright (C) 2015 Markus Ullmann
# Copyright (C) 2026 John Unland (Forked)

set -euo pipefail

# UPPERCASE space-separated country codes to ACCEPT
ALLOW_COUNTRIES="US"
LOGDENY_FACILITY="authpriv.notice"

if [ $# -ne 1 ]; then
    echo "Usage:  $(basename "$0") " 1>&2
    exit 0 # return true in case of config issue
fi

if [[ $1 == *:* ]]; then
    if ! COUNTRY=$(/usr/bin/geoiplookup6 "$1" | awk -F ': ' '{ split($2, country, ","); print country[1]; exit }'); then
        COUNTRY=""
    fi
else
    if ! COUNTRY=$(/usr/bin/geoiplookup "$1" | awk -F ': ' '{ split($2, country, ","); print country[1]; exit }'); then
        COUNTRY=""
    fi
fi

if [[ "$COUNTRY" == "IP Address not found" ]] || [[ -n "$COUNTRY" && " $ALLOW_COUNTRIES " == *" $COUNTRY "* ]]; then
    RESPONSE="ALLOW"
else
    RESPONSE="DENY"
fi

logger -p "$LOGDENY_FACILITY" "$RESPONSE sshd connection from $1 ($COUNTRY)"

if [[ "$RESPONSE" == "ALLOW" ]]; then
    exit 0
else
    exit 1
fi
