FROM rockylinux:9

RUN mkdir /work

WORKDIR /work

# Install EPEL repository and required packages 
RUN dnf install -y epel-release && \
    dnf update -y && \
    dnf install -y sudo ansible python3-libselinux unzip tar crontabs cronie logrotate

RUN rm -rf /etc/*epel.repo

COPY ./ /tmp

WORKDIR /tmp/ansible

RUN rm -f ./run.yml ./inventory.yml

RUN mv ./test/*.yml ./

# Skip galaxy collection install as it's not used by the roles
# RUN ansible-galaxy collection install -v -r requirements.yml && \
#     ansible-galaxy role install -v -r requirements.yml

RUN ansible-playbook --check --become-user root --inventory-file test-inventory.yml test-run.yml

RUN cat /etc/motd
