FROM rockylinux:9

RUN mkdir /work

WORKDIR /work

RUN dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y

RUN dnf update -y && dnf install sudo ansible python3-libselinux unzip tar crontabs cronie logrotate -y

RUN rm -rf /etc/*epel.repo

COPY ./ /tmp

WORKDIR /tmp/ansible

RUN rm -f ./run.yml ./inventory.yml

RUN mv ./test/*.yml ./

RUN ansible-galaxy collection install -v -r requirements.yml && \
    ansible-galaxy role install -v -r requirements.yml

RUN ansible-playbook --check --become-user root --inventory-file test-inventory.yml test-run.yml

RUN cat /etc/motd
