---
#
# Tasks and roles for internal server hosts
#

- name: Configure internal servers
  hosts: internal_servers
  become: true
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  roles:
    - role: k3s
