---
# Add Jenkins helm repository
- name: Add Jenkins helm repository
  ansible.builtin.command: helm repo add jenkins https://charts.jenkins.io
  register: k3s_jenkins_repo_add
  failed_when: false
  changed_when: k3s_jenkins_repo_add.rc == 0 and 'already exists' not in k3s_jenkins_repo_add.stderr
  when:
      - k3s_install_exec == "server"

# Update Jenkins helm repository
- name: Update Jenkins helm repository
  ansible.builtin.command: helm repo update jenkins
  changed_when: false
  when:
      - k3s_install_exec == "server"
      - k3s_jenkins_repo_add.rc == 0

# Check if Jenkins is already installed
- name: Check if Jenkins is already installed
  ansible.builtin.command: helm status -n jenkins jenkins
  register: k3s_jenkins_check
  failed_when: false
  changed_when: false
  when:
      - k3s_install_exec == "server"
      - k3s_jenkins_repo_add.rc == 0

# Jenkins values template file
- name: Put Jenkins values config with jinja2 template
  ansible.builtin.template:
      src: jenkins-values.j2
      dest: /tmp/jenkins-values-config.yaml
      mode: "0644"
      force: true
  when:
      - k3s_install_exec == "server"

# Install / Upgrade Jenkins using helm
- name: Install / Upgrade Jenkins using helm
  ansible.builtin.command: >-
    helm install --create-namespace --atomic --hide-notes -n jenkins
    jenkins jenkins/jenkins --values /tmp/jenkins-values-config.yaml
  changed_when: false
  when:
      - k3s_install_exec == "server"
      - k3s_jenkins_repo_add.rc == 0
      - k3s_jenkins_check.rc != 0
