# Add Jenkins helm repository
- name: Add Jenkins helm repository
  command: helm repo add jenkins https://charts.jenkins.io
  register: jenkins_repo_add
  failed_when: false
  changed_when: false
  when:
      - k3s_install_exec == "server"

# Check if Jenkins is already installed
- name: Check if Jenkins is already installed
  command: helm status -n jenkins jenkins
  register: jenkins_check
  failed_when: false
  changed_when: false
  when:
      - k3s_install_exec == "server"
      - jenkins_repo_add.rc == 0

# Jenkins values template file
- name: Put Jenkins values config with jinja2 template
  template:
      src: jenkins-values.j2
      dest: /tmp/jenkins-values-config.yaml
      mode: "0644"
      force: true
  when:
      - k3s_install_exec == "server"

# Install / Upgrade Jenkins using helm
- name: Install / Upgrade Jenkins using helm
  command: helm install --create-namespace --atomic --hide-notes -n jenkins jenkins jenkins/jenkins --values /tmp/jenkins-values-config.yaml
  when:
      - k3s_install_exec == "server"
      - jenkins_repo_add.rc == 0
      - jenkins_check.rc != 0
