name: Test Ansible Playbooks

on:
  push:
    branches: [ master, main, develop, dev ]
  pull_request:
    branches: [ master, main, develop, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
    - name: Run Ansible syntax check
      run: |
        cd ansible
        ANSIBLE_ROLES_PATH=./roles ansible-playbook --syntax-check -i test/test-inventory.yml test/test-run.yml
    - name: Run Ansible lint (if yamllint config exists)
      run: |
        if [ -f ansible/.yamllint ]; then
          pip install yamllint
          cd ansible
          yamllint . || echo "Yamllint found issues but they are style warnings, not critical errors"
        fi
