name: Test Ansible Playbooks

on:
  push:
    branches: [ master, main, develop, dev ]
  pull_request:
    branches: [ master, main, develop, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Container image
      run: docker build . --file ansible/test/Containerfile.rocky --tag ansible-rocky-test
